# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 749b182d5bd691941af4b21632fa8b1ff7717820ce39bdf0f4ca30eb142ad1ec97918b4703d47eb70010cc802af1d0a738935e7f3574a626ec1dcef1f776ada9

test:
  secret_key_base: 533228157860d3ac70cf5be95af75f8e427b275fb9816ea19fd5a94666dcb70d77719a5f94eb8e9053f638409eba72ada9f652df56bf0cf5674449195ae6f461

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
