# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c4f62385a26d846168fe67b94bca9346eef9a6ad2a6b1d6f269d388bc1f096d05a25c889481d4c315cefc784e2c2695c368bff9c9d7c87502aa55c92b302f7e

test:
  secret_key_base: a24353b1d5ef4d70abed6ea1f72a000e6054050b09a6f497625956e9e352e063d16533b65ab7168f7e09cac6d1f5dc1634ce5512bb90b806d9ed08e03ba8e833

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
